### ISSUE TITLE
day4-cavatica-username

### ISSUE THREAD

**Issue by yuankunzhu** [samesense/bfx-lessons-2019#1]
Opened this ticket to gather attendees' Cavatica usernames for day4 exercises. 
The registration site is: https://pgc-accounts.sbgenomics.com/auth/register. 
Please leave your registered username as comments under this ticket and see you all on Friday.

**Comment by yuankunzhu** [comment]
example:
username for Yuankun: `yuankun`

**Comment by jharenza** [comment]
username for Jo Lynne: `harenzaj`

**Comment by kaichop** [comment]
username for Kai Wang: wangk

**Comment by nathankendsersky** [comment]
username for Nathan: `kendserskn`

**Comment by kpatel427** [comment]
username for Khushbu: `patelk26`

**Comment by afarrel** [comment]
username for Alvin: farrela

**Comment by lauraritenour** [comment]
username for Laura: lauraritenour

**Comment by samesense** [comment]
username for perry: `samesense`

**Comment by MenggeZhao** [comment]
username for Mengge Zhao: `menggez`

**Comment by tanaya-jadhav** [comment]
username for Tanaya: jadhavt

**Comment by fangli08** [comment]
Username for Li Fang: `fangli08`

**Comment by amberwe** [comment]
Username for Amber: amberwe

**Comment by amberwe** [comment]
Username for Amber: amberwe

**Comment by amberwe** [comment]
Username for Amber: amberwe

**Comment by kgaonkar6** [comment]
Username for Krutika: gaonkark

**Comment by bcampbell1231** [comment]
Username for Bruce: campbellb4
